#!/usr/bin/env python3
"""Assemble clean-room Disk II boot (not Apple firmware).

Slot ROM trampoline $C600 → $0300.
Page-3 loader enables the drive then hits assist softswitch $C0F0, which
the machine implements by cycle-driven softswitch sector read → $0800,
then JMP $0801.

A full 6502 denibblizer is deferred (size/debug); Disk II fidelity stays
covered by host/machine/test_disk_rwts.c.
"""
from pathlib import Path


def main():
    # $0300: LDX #$60; STX $2B; motor on; drive 1; Q7L; STA $C0F0; JMP $0801
    page3 = bytes([
        0xA2, 0x60,             # LDX #$60
        0x8E, 0x2B, 0x00,       # STX $2B
        0xAD, 0xE9, 0xC0,       # LDA $C0E9 motor
        0xAD, 0xEA, 0xC0,       # LDA $C0EA drive 1
        0xAD, 0xEE, 0xC0,       # LDA $C0EE Q7L
        0x8D, 0xF0, 0xC0,       # STA $C0F0  assist: load T0S0 → $0800
        0x4C, 0x01, 0x08,       # JMP $0801
    ])
    tramp = bytearray([0x4C, 0x00, 0x03]) + bytearray([0x60] * 253)

    root = Path(__file__).resolve().parents[1]
    (root / "roms" / "diskii_boot_cleanroom.bin").write_bytes(tramp)

    def carr(name, data):
        body = ",\n".join(
            ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
            for i in range(0, len(data), 12)
        )
        return f"static const u8 {name}[{len(data)}] = {{\n{body}\n}};\n"

    (root / "core" / "disk_boot_rom.inc.c").write_text(
        "/* Auto-generated by tools/asm_boot_prom.py — clean-room Disk II boot */\n"
        + carr("A2E_CLEANROOM_BOOT_TRAMPOLINE", tramp)
        + carr("A2E_CLEANROOM_BOOT_PAGE3", page3)
    )
    print(f"page3 {len(page3)} bytes, trampoline 256 bytes")


if __name__ == "__main__":
    main()
